---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  releaseName: cloudnative-pg
  targetNamespace: cnpg-system
  chart:
    spec:
      chart: cloudnative-pg
      version: "~>0.23"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  interval: 15m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    config:
      data:
        ENABLE_INSTANCE_MANAGER_INPLACE_UPDATES: "true"
        INSTANCES_ROLLOUT_DELAY: "10"
