apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  valuesFrom:
    - kind: ConfigMap
      name: tailscale-values
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientId
      valuesKey: clientId
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientSecret
      valuesKey: clientSecret
