---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: project-contour
  namespace: flux-system
spec:
  interval: 60m
  timeout: 5m
  releaseName: project-contour
  targetNamespace: project-contour
  chart:
    spec:
      chart: contour
      version: "19.5.8"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: project-contour-values
