apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - wildcard-cert.yaml
configMapGenerator:
  - name: project-contour-values
    namespace: flux-system
    files:
      - values.yaml=project-contour-values.yaml
configurations:
  - kustomizeconfig.yaml
