# https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingloadbalancer_topic-Summaryofannotations.htm
envoy:
  service:
    annotations:
      oci.oraclecloud.com/load-balancer-type: lb
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10Mbps
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 10Mbps
      service.beta.kubernetes.io/oci-load-balancer-shape: flexible
      oci.oraclecloud.com/ingress-ip-mode: VIP
      service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
      oci.oraclecloud.com/oci-load-balancer-listener-ssl-config: '{"CipherSuiteName":"oci-default-http2-tls-12-13-ssl-cipher-suite-v1", "Protocols":["TLSv1.3"]}'
      service.beta.kubernetes.io/oci-load-balancer-backend-protocol: HTTP
      service.beta.kubernetes.io/oci-load-balancer-tls-secret: wildcard-cert
      # service.beta.kubernetes.io/oci-load-balancer-tls-backendset-secret: <value>
      # oci.oraclecloud.com/oci-load-balancer-backendset-ssl-config: '{"CipherSuiteName":"oci-default-http2-tls-12-13-ssl-cipher-suite-v1", "Protocols":["TLSv1.2", "TLSv1.3"]}'
      # service.beta.kubernetes.io/oci-load-balancer-connection-idle-timeout: 60s
  containerPorts:
    http: 8080
    https: 8443
