envoy:
  service:
    annotations:
      # INFO: All annotations are available at https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengcreatingloadbalancer_topic-Summaryofannotations.htm
      oci.oraclecloud.com/load-balancer-type: lb
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10Mbps
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 10Mbps
      service.beta.kubernetes.io/oci-load-balancer-shape: flexible
      service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
      oci.oraclecloud.com/oci-load-balancer-listener-ssl-config: '{"CipherSuiteName":"oci-default-http2-tls-12-13-ssl-cipher-suite-v1", "Protocols":["TLSv1.3"]}'
      oci.oraclecloud.com/security-rule-management-mode: NSG
      oci.oraclecloud.com/oci-network-security-group: ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaafrdfn54r6aeb3hqpsl7ob2ggffqazvnum3ort73h5ytf4h7zg6fa
      oci.oraclecloud.com/ingress-ip-mode: VIP # Would be nice to switch to proxy

      # service.beta.kubernetes.io/oci-load-balancer-backend-protocol: HTTP
      # service.beta.kubernetes.io/oci-load-balancer-tls-secret: wildcard-cert
      # service.beta.kubernetes.io/oci-load-balancer-tls-backendset-secret: <value>
      # oci.oraclecloud.com/oci-load-balancer-backendset-ssl-config: '{"CipherSuiteName":"oci-default-http2-tls-12-13-ssl-cipher-suite-v1", "Protocols":["TLSv1.2", "TLSv1.3"]}'
      # service.beta.kubernetes.io/oci-load-balancer-connection-idle-timeout: 60s
  containerPorts:
    http: 8080
    https: 8443
