---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-cd
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/argo-cd/overlays/freeloader
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: external-secrets
    - name: project-contour
