---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: platform
  path: ./apps/certificates/overlays/freeloader
  prune: true
  wait: false
  timeout: 5m0s
  dependsOn:
    - name: cert-manager
