---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: platform
  path: ./apps/external-secrets-operator/base
  prune: true
  wait: true
  timeout: 5m0s
