---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./configs/external-secrets/base
  prune: true
  wait: true
  timeout: 5m0s
  dependsOn:
    - name: external-secrets-operator
