---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-localpv
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: platform
  path: ./apps/openebs-localpv/overlays/freeloader
  prune: true
  wait: true
  timeout: 10m
