---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: platform
  path: ./apps/podinfo/base
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: project-contour
    - name: tailscale
