---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: project-contour
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/project-contour/base
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: certificates
    - name: external-dns
