---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: "~>6.8"
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 15m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  values:
    redis:
      enabled: true
      repository: public.ecr.aws/docker/library/redis
      tag: 7.0.6
    ingress:
      enabled: true
      className: contour
      tls:
        - secretName: wildcard-cert
          hosts:
            - podinfo.cloud.blacksd.tech
      hosts:
        - host: podinfo.cloud.blacksd.tech
          paths:
            - path: /
              pathType: ImplementationSpecific
