---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: do-token
  namespace: external-dns
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-oke
  target:
    name: do-token
    creationPolicy: Owner
  data:
    - secretKey: do-token
      remoteRef:
        key: DigitalOceanZoneManagement
