---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  values:
    provider:
      name: digitalocean
    env:
      - name: DO_TOKEN
        valueFrom:
          secretKeyRef:
            name: do-token
            key: do-token
    sources:
      - service
      - ingress
      - contour-ingressroute
      - contour-httpproxy
    extraArgs:
      - --contour-load-balancer=project-contour/project-contour-envoy
    domainFilters:
      - cloud.blacksd.tech
    txtOwnerId: freeloader
    interval: 5m
