---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: argo-cd
  targetNamespace: argo-cd
  chart:
    spec:
      chart: argo-cd
      version: "~7.8"
      sourceRef:
        kind: HelmRepository
        name: argo
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: argo-cd-values
