---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 60m
  timeout: 5m
  releaseName: envoy-gateway
  targetNamespace: envoy-gateway-system
  chart:
    spec:
      chart: gateway-helm
      version: "v1.2.4"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: envoy-gateway-values
