---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials-velero-sync
  namespace: velero
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-s3
  target:
    name: s3-credentials-velero
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .AccessKey.AccessKeyId }}
          aws_secret_access_key={{ .AccessKey.SecretAccessKey }}
  dataFrom:
    - extract:
        key: S3CredentialsVelero
  # data:
  #   - secretKey: access_key_id
  #     remoteRef:
  #       key: S3CredentialsVelero
  #       property: /AccessKey/AccessKeyId
  #       decodingStrategy: Auto
  #   - secretKey: secret_access_key
  #     remoteRef:
  #       key: S3CredentialsVelero
  #       property: /AccessKey/SecretAccessKey
  #       decodingStrategy: Auto
