---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials-velero-sync
  namespace: velero
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-s3
  target:
    name: s3-credentials-velero
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .access_key_id }}
          aws_secret_access_key={{ .secret_access_key }}
  data:
    - secretKey: access_key_id
      remoteRef:
        key: S3CredentialsVelero
        property: /AccessKey/AccessKeyId
    - secretKey: secret_access_key
      remoteRef:
        key: S3CredentialsVelero
        property: /AccessKey/SecretAccessKey
