---
configuration:
  volumeSnapshotLocation: []
  backupStorageLocation:
    - name: oracle-cloud-bucket
      provider: aws
      bucket: velero
      prefix: blacksd
      default: true
      validationFrequency: 24h
      accessMode: ReadWrite
      config:
        region: eu-frankfurt-1
        s3Url: https://blacksd.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
        s3ForcePathStyle: true
credentials:
  useSecret: false
