---
configuration:
  volumeSnapshotLocation: []
  backupStorageLocation:
    - name: oci-bucket
      provider: aws
      bucket: velero
      prefix: freeloader
      default: true
      validationFrequency: 24h
      accessMode: ReadWrite
      config:
        # TODO: region and s3Url should be a param derived by in-cluster secrets
        region: eu-frankfurt-1
        s3Url: https://froaw0vigiem.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
        s3ForcePathStyle: true
credentials:
  useSecret: true
  name: s3-credentials-velero
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.0
    volumeMounts:
      - mountPath: /target
        name: plugins
