---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: tailscale-operator
  targetNamespace: tailscale
  chart:
    spec:
      chart: tailscale-operator
      version: "1.90.8"
      sourceRef:
        kind: HelmRepository
        name: tailscale
  install:
    # createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: tailscale-values
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientId
      valuesKey: clientId
    - kind: Secret
      name: tailscale-oauth
      targetPath: oauth.clientSecret
      valuesKey: clientSecret
