apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - namespace.yaml
  - tailscale-oauth.yaml
configMapGenerator:
  - name: tailscale-values
    namespace: flux-system
    files:
      - values.yaml=tailscale-values.yaml
configurations:
  - kustomizeconfig.yaml
