global:
  scrapeInterval: 90s

cluster:
  name: freeloader
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    auth:
      type: basic
      username: "2355589"
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-012.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "1173472"

# https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-cluster-metrics/values.yaml
clusterMetrics:
  enabled: true
annotationAutodiscovery:
  enabled: true
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
clusterEvents:
  enabled: true
# NOTE: OCI natively doesn't play nice with Alloy; local log pesistence needs to be enabled
#       see https://github.com/grafana/k8s-monitoring-helm/issues/1042
nodeLogs:
  enabled: true
podLogs:
  enabled: true
integrations:
  alloy:
    instances:
      - name: alloy-metrics
        labelSelectors:
          app.kubernetes.io/name: alloy-metrics
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name: [alloy-logs, alloy-singleton]
        metrics:
          tuning:
            useDefaultAllowList: false
            includedMetrics: [alloy_build_info]
# TODO: drop some Alloy internal metrics
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-logs:
  enabled: true
