---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-oke
  target:
    name: digitalocean-dns
    creationPolicy: Owner
  data:
    - secretKey: do-token
      remoteRef:
        key: DigitalOceanZoneManagement
