apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  valuesFrom:
    - kind: ConfigMap
      name: alloy-values
    - kind: Secret
      name: alloy-token
      targetPath: destinations[0].auth.password
      valuesKey: alloy-token
    - kind: Secret
      name: alloy-token
      targetPath: destinations[1].auth.password
      valuesKey: alloy-token
