---
cluster:
  name: freeloader

destinations:
  grafana-cloud-metrics:
    type: prometheus
    url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    auth:
      type: basic
      username: "2355589"
  grafana-cloud-logs:
    type: loki
    url: https://logs-prod-012.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "1173472"

global:
  scrapeInterval: 120s

# -- Kubernetes observability --

clusterMetrics:
  enabled: true
  collector: alloy-metrics
  kube-state-metrics:
    metricsTuning:
      useDefaultAllowList: true
  kubelet:
    metricsTuning:
      useDefaultAllowList: true
  cadvisor:
    metricsTuning:
      useDefaultAllowList: true
      excludeMetrics:
        - container_blkio_.*
        - container_tasks_state
        - container_memory_failures_total
        - container_fs_io_.*
  apiServer:
    enabled: true
    metricsTuning:
      useDefaultAllowList: true
      excludeMetrics:
        - apiserver_request_duration_seconds_bucket
        - apiserver_response_sizes_bucket
        - apiserver_watch_events_sizes_bucket
  controlPlane:
    enabled: false

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
    metricsTuning:
      useIntegrationAllowList: true

annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics
  annotations:
    scrape: prometheus.io/scrape
    metricsPath: prometheus.io/path
    metricsPortNumber: prometheus.io/port

prometheusOperatorObjects:
  enabled: true
  collector: alloy-metrics
  serviceMonitors:
    excludeNamespaces: [kube-system]
    metricsTuning:
      excludeMetrics:
        - .*_bucket
        - .*_sum
  podMonitors:
    excludeNamespaces: [kube-system]
    metricsTuning:
      excludeMetrics:
        - .*_bucket
        - .*_sum

clusterEvents:
  enabled: true
  collector: alloy-singleton

podLogsViaLoki:
  enabled: true
  collector: alloy-daemonset
  excludeNamespaces: [kube-system, flux-system, velero]
  extraLogProcessingStages: |-
    stage.match {
      selector = "{namespace=\"grafana\", app=\"alloy\"} |~ \"level=info\""
      action = "drop"
    }
    stage.match {
      selector = "{namespace=\"argo-cd\", app=\"argocd-repo-server\"} |~ \"level=info\""
      action = "drop"
    }

nodeLogs:
  enabled: true
  collector: alloy-daemonset
  extraLogProcessingStages: |-
    stage.match {
      selector = "{unit=\"kubelet.service\"} |~ \"level=info\""
      action = "drop"
    }

# -- Self-monitoring --

integrations:
  alloy:
    instances:
      - name: alloy-metrics
        labelSelectors:
          app.kubernetes.io/name: alloy-metrics
        metrics:
          tuning:
            excludeMetrics:
              - alloy_component_dependencies_wait_seconds_bucket
              - alloy_component_evaluation_seconds_bucket
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name: [alloy-daemonset, alloy-singleton]
        metrics:
          tuning:
            useDefaultAllowList: false
            includeMetrics:
              - alloy_build_info

# -- Collectors --

collectors:
  alloy-metrics:
    enabled: true
    presets: [clustered, statefulset]
  alloy-daemonset:
    enabled: true
    presets: [daemonset, filesystem-log-reader]
  alloy-singleton:
    enabled: true
    presets: [singleton]

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
