apiVersion: v1
kind: Secret
metadata:
  name: do-token
type: Opaque
stringData:
  do-token: ENC[AES256_GCM,data:3pOEDX0yU7T+cxDmnbGRnPReyE09/7FM7AAgGZ6oD69ZP0xWZgBq4UKtZV6Tz6mibAioVtBmkzV/fqb0j3oPjAe3fSQ6das=,iv:BYjOJ1Lt+YFfOXv/gI6JgAMXffeKW2yvRy5cZk2BBTA=,tag:GZyh6DJdMDcdomwNkHc6EA==,type:str]
sops:
  age:
    - recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdUZqUHd0YVRCOHpMbTlU
        SEdIc056bDFrT1p3MEZzV2piM05lOVIvRDFNCjdBZFVPS2k0S1EvSzJkeE9MSFdn
        cDRWVEs2T0tXRmdLU1pxN3JhU09sZjQKLS0tIExEcUl6TGxvaGY2ZzkyakhyL2FF
        MGtTUEkxVHMzaHl0RE9jbzdPQ2hRdlkKcClG+Nsv26qKNzIlYgBJtObKwqlkSkEl
        QHVIfsUMvjuMT11BAti0xgFfYJUWI7rWRQms7vIN3Qpfnx4YvTImNA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZGRmdm93VXJsQ3VlSzU2
        SWpaVWgvNzR1QlRWUXpBZ2dIeERaakZyY21RCjN5UEczYW01RWNjTEZtejRyNG44
        TkNoeE9nVnROZTE3ZFFJK0pkd20vQmcKLS0tIDRBSUN3WDFaUmFuWDRIU2czWmJZ
        Q0ZVWE45SW9aS3paOWp3UkNzQUQ4aHcKLfcGf40aspGNG+KwVgzNmXCJkRQWZgXq
        dFRvgdD4imsXGGNWyNMhXTYbUQ0f4xPEOYL+xi7gCxmlbeVMTeNS8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T22:28:37Z"
  mac: ENC[AES256_GCM,data:ZU8Y5wL7Ili8Z+qW/l9mowk0tcBsL1dKs4+YWAsOn6JnSORiYxYImhi9c6bBVXmuUM/YZcgGGyc+ZBONfuXmWBwNeyCQ5vD/gBe4s49bUYAt7zIc4ChOCA3UIB4PrL0NM2lePVHYRWFDNLQJwvZezYJc69s9DkOh8ucjnbLeHX4=,iv:p7nphm2HJw74iukseNiMz6+qAEy6lFzBdjfj3RxJK/I=,tag:tPYj3O41EQkerXvmq1Fb5Q==,type:str]
  pgp:
    - created_at: "2025-12-26T22:28:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA2fheYx7el0jAQ/+OPynpFRZ1+FJrLVdPuf6Lmplsw+/HlnAGNVISzeh8sbg
        yZCyrFU2D8kHw75Hw/swYKBvfxrsDu6nmct31q2O7R2ujapyBf5fhMAJxrjNXSHy
        Y6WGPQIvuOWhs412NbeWCdxG8fLkAytwV9yLnzPkoyFs6h6iyuvPIWIHuh/MGG/L
        yPf0v3UbK1qHADldukJtdhcazE1KNutGUZmLduXPVWDV9OSnFakofu6sFn8i2Rnh
        E5CGyI+UmouD6CfvfCx/tm1rRya3d8wWljHfuyhF6lUG/+O8ofS8AgxcMxtUif9G
        vUy41SNAhSmdlLLqEf3v/ypHoIPT1dAQdi5uEGYPfkPthBFntThXYK4mVa2OQX0G
        dIwA63ER+N0PsDtclDaKCZ6aHT1vb3gAOsLMBm4aTwKOrkASShqvhBYzb3Ld9tc4
        MZlvv6LcUeyy8kkIFSeAMvalR5/weeYhL81ecHCA2Xs9dVV5FCqFiSyaVcD0+fF8
        n97muOoCk2SHUYj7Em4PTXzAr5u5UfMpKticde6QzCeBpoBNZ0AMRC+pkptBvDJy
        ykuVtk414aQ/akLvVM858QbdNbcNaKUSD2YciRc0D8HR/WTFkEqM+OuFSq0AcELz
        P3D9VvvMlwuYUNMZ/aDP5FIOHRRyUwHv0vosk39QTiiC7Uxrg1jI7Afq7xsZYgHS
        XAGKZN4tchWHMCS20+iPx9va6ebQHvxyhNMpoyomYFKM1hhpsteopWWSGiVds0xF
        MV3l1djlUC9fF/da/RCY4cNkmot9igvLBiGD3Za33IONE/rZTRkRi3d6ExzS
        =84nV
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
