apiVersion: v1
kind: Secret
metadata:
    name: do-token
type: Opaque
stringData:
    do-token: ENC[AES256_GCM,data:EiIh3RvFw3WS3KHAZuyCgTSDGpQoscdJribMZbg2227Pl8fee+7oxTm+JmUpluOtBv8vrQaGOTg6qZ6qQjMjJTeQfWBX6yU=,iv:pspIEyfjSia+CseO5biTlv5Ch9dHi1LWZWtlB391a8c=,tag:ofIt0hdq+YrBl5nE6S+tBA==,type:str]
sops:
    age:
        - recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeFN1cnpzdU9pWHRuZDdX
            RGg2amkveU1hTFlGaERlUXJaZTVWb1FtTlRBCnJHWkQ3eldHZWFKZ1dpWHU2UEdS
            RGcxN1VaWU1IdU9tWUhYM0xmS1o2Ym8KLS0tICttZzMvakRZcDlwNWZjSW5hLytr
            L05lSFovNTJkYlhQbTBLM3pXMFZCU3MK/8NRSUW2lTn0K03oubUkd2ZnnGRzzrc4
            u1tUeQzaihUclSGYhW3RKgcYVhqkVPG+5JBCwWoyZTrbejhVe8I6sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OWZvRGV1ZVpVV21GVDNS
            MHp5Vk50UmJlVTFvbUxHZC9VQTlQNy9CTFhrCkpMNnVub0xZa0tlT1dndzdYWUgz
            K0lTbGdXbGRMZzZhOUJmZUpzUCtEczgKLS0tIGdIM0V6MGFLWklQQ09wZ2lCazlV
            N2EvMG1aZnZvckhScFNEQnlNUHZRMzAKvDUkD+h0Y3vH6YkM3EurTPcGo5Tj28IV
            CvMtGN6TGWoi6xWh6oPYTrEYd6Rx0zp59dR97J4HhGcexcXEtCtjNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T17:06:39Z"
    mac: ENC[AES256_GCM,data:X+5Zmm5SJbnqYMDA15dkciYiCdcHoWjTDxCyQyMGkfDSXPTMKUvpKp5RucLcjmGV0JqWXg5MOw7ssExOFCpetHfFHVZbMSr5vMyuT0/As2bKQ3Swa9ELot86uMcV7mCfZiN2REazpq9NfIkQ2WXtXrH+mRyIL3iAoWLqdnCkjVQ=,iv:na4MT4F+cfrjASVQi9Esu1F8+m8tmviLaEfg+0Kr9Ls=,tag:bIgvQFAXFySU6eV2cyaMvA==,type:str]
    pgp:
        - created_at: "2025-12-24T17:06:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2fheYx7el0jARAAp+3y425LR6K3F+kqtanpttDYDsLVRJSlpNJMj0EjJt9m
            tzk/g7PT6bXUSgb5lE0ie5H3SRuLsA/OfZOMQYWlBAotGGXe66ShObsqlPXQBM0u
            3djoyv5AH9MlN68vPFdao7W74erhGfwTNf774NZaZGB21Qm+qvL7HEHfbq2oqxmU
            4bsflMVufL8fxhPv0b68J6ZwgOjh6bP2t3zaQDJMA33/Fhw4qKjNLlNKDeCw2lhU
            ewdG6xk0MwlkS7frE2zC2PvYqI6l1mZinS1v2yiUT03dTPVhoqmp6ouIJW2q1lNf
            yAf5vwTlRaB4mUwAcot9qwdriv5tHq/6F+wA7ax9Duc33g6gKUbq/WCERsGDDszo
            awvQ3xj9hhhYHMY336Sy4xTplxu7thScV8pzNk2dmcwvKsXuwNVJ03qVoz2fbAJF
            ml7rgAMIpKIz1a1oJU8ZsQw3ZwFDlCcpvR0BwW/r+YXxPM9+qYV33DQjVD4JKA6F
            EN5oCnMKDkixjt4COl2AluLOj1zG01hvQo39fbGaMMLIwqvY13OoWGTUyeVH6HUN
            znQMJ/YZRkQjY4tURaFFOPGzyYEA8Kc4xCoWq++TvYfU6EcPbFJO4so5q9ud4E5Y
            y3czCJYC0Alap3v4dCCSkBQhDbDACMu6HOCyWP68QjrDrpBhK6ENEcEHVdiUg2/S
            XgF4GJkzOlXL+1cxQqrwFN+YyJQ51A1aaIOoAgnJLuEtZxbhKBpoduXl/u9LI9tE
            Dc3yeWH1B8l5Fwo9n1hTeNLMVzWNisN8zuHUEB2eJg2AqQVv3psj52gtEX5YQQo=
            =9yzo
            -----END PGP MESSAGE-----
          fp: B31C0D06E2C1EB5A
    encrypted_regex: ^(stringData)$
    version: 3.11.0
