apiVersion: v1
kind: Secret
metadata:
  name: rfc2136-tsig
type: Opaque
stringData:
  keyname: ENC[AES256_GCM,data:9PUu0gaZiU5UN4a/QFFbgSGF5bYpGLoeeO6HTt8=,iv:LbcQo5b+5o+1LeD+34QeOrmWrBmVzIBhNs8rNlSI0Oo=,tag:MHx41/XyJPFJzyrK/pX+HA==,type:str]
  secret: ENC[AES256_GCM,data:+sB9Nj56ETmxYoSXjKO4xkNXrpBQs/bxrLs0rjtCHPedTJDLR0JjTd6Psy4=,iv:lBD6USTmdfRnO53RXc55FkuVVpbJbi1SnfLNSw2uQW4=,tag:oeTWxWWV3BtzEzWA4yZpNg==,type:str]
sops:
  age:
    - recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cWpoVE5lZmFITWlHdTF0
        eXgvTzcza3E3YjVBdHNMNVo1R0VxTXJRWEc4CmdXS1hNOHIzVEJRMHNxbUwvSGhI
        NVBYWGpsK0h1d2p4eGxQR3pSLzhYWk0KLS0tIG5xWkxNOGNhQ29CbDg1Q1BYSkpJ
        ZHcvcGVnaEIwMlEvaUZOS0FEa0JrbEkKHSG/2wt+Qe990cPd996j1yeupN3ERlIB
        ytpAPeigkMd78alA74aee5Yp0qt3EqFXE3qrNIB+vqo8XSHqVd5qwg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQWxMcFZvWDFvMHNiUW4x
        ZVZ0Z0VxNHVMMytDc1lCUzVOVlBNTHRGY2hvCnV0UkRjbGMyTm45R1poejN5RGVv
        eTlLS243UVp4R2ZiUXlGUldKenhyWXMKLS0tIERSazZRSVhIeEJvT1VNUG9HTjZk
        dTRCdFlia0VWQ0E5QVlLQ1RFRjJjVDAKHieco0/qHvAzIIu0kqjUQ/eXxgF8db1t
        ZtmvrDfPqitBN8axZD2d9HAxCahFsMoMjNIfA6ZD4vkIWYPtBDstmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-24T07:38:45Z"
  mac: ENC[AES256_GCM,data:M/bjnMI3TIYLvRAno+oQ3NhWRC8v/8RdiNBvteBjL8QgO3JUlsC6o4wq/bmqL2lA49LiRCciWRaoZG1gBQej2zNrUG8YCagJelg7MwO3lJDj8R9D0bg3x/zouChCAJSl/wAxsjyd0Z3KUzL6VMFbOfKQWQc1lwI265PXyrh9Cos=,iv:llKoG2CSqi66wqXvVYG3pVKPcmggnUbY7jlurzANee8=,tag:NC18YuTWFwWGXDej5lYWug==,type:str]
  pgp:
    - created_at: "2026-05-24T07:33:11Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ//VhmEAMxekcS22pSNUHYVAe1C9PjOvgcFtAVIVNACrHAx
        TIzPA0jYGXaSdtLvqmNx9AFWddC5eRMkL+MGExipc3CQUonKudln5FDG9GPYtrwp
        g4NY8Nbk1/9E5ozPYJ/8CrrGdA1pWl0HN8myf2dffYtuWtTILd9Wlc2hCkXcoypQ
        mmKIK7sYixNBHLn/fdPYbr8CadI1vntUROUYXvM0hyu17UBHY1ZSPqTiBKQn9prA
        rV03t3/VaMIJT6gU9phxk8PB0xZXDu5wEBzz/HC6U4dt1hi/9BriyajHpZyjnd82
        UQ5w4wYumUCbFlYNDvevpJSybg+TWJnfIyxjBg5h+YTqY0Pr2nflIX6kuRD+E0c6
        ZMPRFQmZPmbKZAoQmwHFEkkhGiHtOBCrsg/UbiFxVkRaNxlngXHJ9V6ozKogpdHu
        wehNSJtvvb3z651SXYgN4GbTDZFMMuyJ5fSEaef4pR0yM4fzMd1hw8pZOMksAf8D
        RSusCZEAuY/o+0TJvLgahc8fZ+Z03lLtvxVygQS1sY421fofIoPWNtdBKz+Z2Joz
        ZkZtiyTecEr/OX+82+OYRTPqzDdG/BOGd4j3oM5UEdgOovLseI1LKN6yBXnwYL3g
        xXPWRRYwYfGS1zajL3KHzQokmvF0UPztfLkSEUdSETBZlPpHFKkuG6OSwMfyKVbS
        XgEcR2zxnquerRNUDk1HVyNlz1AsQIMQA2sAduauj/PBVbH/Q0df7ScmBhKWF5D7
        quzaGp2Oxx9URrstf48+qJAZ58qZsD8iXWqL6nqBei7NPdE0HQqE8D/WysQGqjs=
        =263a
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
