apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-smtp
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:fY7M+Rl31SATF8fgDZo2BSaGlgB7GT3pR7vOMYByBMmnpsCez6UXm8aF984Q/98gAF2kSEEyf1WCN9/sTRQ6a8xsV1WuW7BIOwim7Eu0hoOx7JUf02kJbnqA20HDoslJAk97X1APR8yI0BDsQ5U6Isg+zhGoZ46vcWz7aKsvUjtqdNNXUu8qWN9enT/5lj+gkndpKJ8ly5OdCx02WyhumZ9/3Q==,iv:4idqNSXHFwnGdmjdv3V2EpRlYT5ZUgmTWP30UZoLVzs=,tag:hdB/UQ1Jr7a9SEHaFD4rfg==,type:str]
  password: ENC[AES256_GCM,data:1ov6BkSnjkRA3exqM3erpd6KlmE=,iv:Q0NiMHxVYgImMPZSXAKUL0xC/pRQT05NKrSU+E7j6xQ=,tag:C+fYVEa+2UcRqt4SjOL1vA==,type:str]
sops:
  age:
    - recipient: age1rqldalz0wppytnn5qzkms98awx43u2kkea878wslktyu6sjrq35sfzktv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2azNGNTVPQ3BGZERtSlFt
        NGhKZlhVYmtOdTkxNENiWTMvZkdMelRPLzAwCm1aQzZ2bXgrZCt5TEZsdkEyN1FQ
        ZFFCeUlqSlN5MWtlV2xYR1Rqay9YcFUKLS0tIG9QNEJoSU4vbUZPRmR2bkJCeHRp
        K1RoY0RPM2ViQTA1ZkkrUmo3YVU0L1UKRcQUVnwv4WhV7iZRQoZgqArMBA9dg06U
        /+XRz0Ot9DxylLNANxvqySbmztc+YGdS/HNMy3QUcuWQByqQJcpaHg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdEU0TFYxSnBCTkUyQ1JM
        UmRTbCthb1hzZEtzUVJ5LzVnOFVERytsNmxVCndMZjZMa0gvTFJ3OERQdlZDOHJ2
        QTM4UDhodHZMbCtxRDVPcXBJdDRNYlEKLS0tIDdQS28xZm5CUDg4Z2lEL1Zycjhv
        dyt5SWEwRmNxbkRKN0k0U2dEU3ZaRmcKnH32n97T3QCioqJjZ0WgslMtdtOG16+U
        drD4WCRS2Is2oik4mld30ks4B65LU3sEPSHFEA8JuY54Ab9ggbkeow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-24T16:10:28Z"
  mac: ENC[AES256_GCM,data:KbinParowLvtxCH8YxKCnDkbAF1ZKEBh8RX1LmLBOuu4qEOkdYiyqcttzB/YJiGqzjZQvmssbLlyFhPx+GRr8d+QVwhF3sEeY+fS7UKzq7DoSxIR2D3YArHnL8Nelr9RJwPqAKvBv+cmoSFCp9frsuYauVlt/WIBrBzwKwRr9Xo=,iv:k6E0RTx0i/u8WFMU0jTFSP/XeSTvY92SpfgOKskEI7o=,tag:UmaNAeuO/fGxYWzhn8JoYg==,type:str]
  pgp:
    - created_at: "2026-05-24T13:02:40Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ//eHVKqPixkwH0nnAkenjqSB2lXtukiQfyRL3OLF9KASb5
        0JBaAA9JGKP57mcaSS+D/Rsr46Uq4GJ+DltVyY7kq4hiktv6Z4N6STaGJbyDu03/
        W4Cbs0261CRtC7G2mOPXKaf2xdIqSHYRk8MTYCMPC87SlNK7psZmxGUeTXLFJiKa
        sHIFqNaAr7r9RCZ3v0cnD83CWbeUev4x8GPNCKEWQYkadn9g8CKXwk2p2nLvtAKN
        zpgj0aa3VCV837ZsakHVsaZ4d/V17ujhD+RBDfpw7z7TZtH7ikQicGnchLu5/AAZ
        sx8KCP7vf3pkgXmh9XPKgs/jtuztEoa4v0qJ6wUjIVNfCxrdYFC1cFR6ja1mb6TS
        6sJEfbvjAtNcoBfK7SkSt7ZzYPRnmvMXMJInaxQV0GCGpZ8j1LBahFXESylxUMgl
        +IjYfX3tYMoa3X2OzLKGdlBeO/gxVpRlAnGpIbE/DjjgLGTwW6g4FpF/RxLIPl08
        2ar3iv4wp34m4PDI+gVXu2cnrWOiF++w6ytzcQnM2uMzp+D74nkvyxTfc36cMpjw
        FSgB7XMjH7iGS+LgyOo56BtMWFgy4crt+wDlmEcUhzNoaivXR9ML8Od6QrFXMVDa
        CGZhJhfEMLcIFAupgF0wVDPx0pcrvI0l5jUTFYuzTjQe+ttg0kSURgJlfhPm0nXS
        XgEqbvP0pw2nOCer2MgJ7RQ3q4ZsAvgo201L62Dm+0KDQta8MYye9p9Eg5dKYzj3
        k3mS8FNNHAFM5JRyep9Oc0nqvK47sdMCKeJabUY0dZYmw6tBFYbMjOikvTy3aSc=
        =gLVc
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
