apiVersion: v1
kind: Service
metadata:
  name: flux-webui-ts
  namespace: flux-system
  labels:
    app: flux-webui-ts
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: flux-freeloader
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: flux-operator
    app.kubernetes.io/name: flux-operator
  ports:
    - name: http-web
      port: 9080
      targetPort: http-web
      protocol: TCP
