---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: external-dns
  targetNamespace: external-dns
  chart:
    spec:
      chart: external-dns
      version: "~1.15"
      sourceRef:
        kind: HelmRepository
        name: external-dns
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
