---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: do-token-cluster-sync
spec:
  externalSecretName: do-token
  refreshTime: 60m
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - cert-manager
          - external-dns
  externalSecretSpec:
    refreshInterval: 12h
    secretStoreRef:
      kind: ClusterSecretStore
      name: oci-vault-oke
    target:
      name: do-token
      creationPolicy: Owner
    data:
      - secretKey: do-token
        remoteRef:
          key: DigitalOceanZoneManagement
