---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  timeout: 5m
  create-namespace: true
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "~0.14"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    ingress:
      hosts:
        - host: podinfo.production
          paths:
            - path: /
              pathType: ImplementationSpecific
