apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kube-shared-secrets
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          key: ca.crt
          namespace: external-secrets
          name: kube-root-ca.crt
      auth:
        serviceAccount:
          namespace: external-secrets
          name: external-secrets
      remoteNamespace: shared-secrets
