apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: wildcard-cert-cluster-sync
spec:
  externalSecretName: wildcard-cert-sync
  refreshTime: 60m
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - podinfo
          - argo-cd
          - project-contour
  externalSecretSpec:
    refreshInterval: 12h
    secretStoreRef:
      kind: ClusterSecretStore
      name: kube-cert-manager
    target:
      name: wildcard-cert
      creationPolicy: Owner
      template:
        type: kubernetes.io/tls
    dataFrom:
      - extract:
          key: wildcard-cert
