---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: velero
  targetNamespace: velero
  chart:
    spec:
      chart: velero
      version: "~9.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: velero-values
