---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: platform
  path: ./apps/certificates/overlays/understairs
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: cert-manager
