---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: platform
  path: ./apps/csi-driver-nfs/overlays/understairs
  prune: true
  wait: true
  timeout: 10m
