---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: platform
  path: ./infrastructure/secrets/overlays/understairs
  prune: true
  wait: false
  timeout: 10m0s
