---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: platform
  path: ./apps/tailscale/overlays/understairs
  prune: true
  wait: true
  timeout: 10m0s
  # INFO: the key location is set in the controller, as per https://fluxcd.io/flux/components/kustomize/kustomizations/#controller-global-decryption
  decryption:
    provider: sops
