---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: smtp-cluster-sync
spec:
  externalSecretName: smtp-creds
  refreshTime: 60m
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - vaultwarden
  externalSecretSpec:
    refreshInterval: 12h
    secretStoreRef:
      kind: ClusterSecretStore
      name: kube-shared-secrets
    target:
      name: smtp-creds
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: smtp-creds
