---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault-oke
spec:
  provider:
    oracle:
      compartment: ocid1.compartment.oc1..aaaaaaaay2utjka6iga2alxinawlm5ryj4lxst74q2ns7ela26f7cl73xjrq
      encryptionKey: ocid1.key.oc1.eu-frankfurt-1.ent2pnqxaabs2.abtheljs4tz655x3n6vk4b77qrhfl4oidnmrlkhb5uoecam6o2tu74wkcueq
      principalType: InstancePrincipal
      region: eu-frankfurt-1
      vault: ocid1.vault.oc1.eu-frankfurt-1.ent2pnqxaabs2.abtheljswhbjezzyumscqfsjw5o6467yyi4wnr5kzlkx3eacwiwsixmkwnfa
