---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  releaseName: alloy
  targetNamespace: grafana
  chart:
    spec:
      chart: k8s-monitoring
      version: "~2.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    # createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: alloy-values
    - kind: Secret
      name: alloy-token
      targetPath: destinations[0].auth.password
      valuesKey: alloy-token
    - kind: Secret
      name: alloy-token
      targetPath: destinations[1].auth.password
      valuesKey: alloy-token
