apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-frankfurt-1.ent2pnqxaabs2.abtheljswhbjezzyumscqfsjw5o6467yyi4wnr5kzlkx3eacwiwsixmkwnfa
      region: eu-frankfurt-1
      compartment: ocid1.compartment.oc1..aaaaaaaay2utjka6iga2alxinawlm5ryj4lxst74q2ns7ela26f7cl73xjrq
      principalType: InstancePrincipal
