apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: letsencrypt-account-key
  namespace: cert-manager
spec:
  refreshInterval: 24h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: oci-vault
  selector:
    secret:
      name: letsencrypt-account-key
  data:
    - match:
        remoteRef:
          remoteKey: LetsEncryptAccountKey
