---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs-localpv
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  releaseName: openebs-localpv
  targetNamespace: openebs
  chart:
    spec:
      chart: openebs
      version: "~4.4"
      sourceRef:
        kind: HelmRepository
        name: openebs
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: openebs-localpv-values
